### ISSUE TITLE
indentation error

### ISSUE THREAD

**Issue by aarthiprashanth13** [DinakaranP/Ena-Download-#2]
![Screenshot 2022-07-28 104621](https://user-images.githubusercontent.com/109646134/181426147-bde848b2-a521-4bdf-8838-98cba803cfea.png)
![Screenshot 2022-07-28 104634](https://user-images.githubusercontent.com/109646134/181426155-d5ca4fcb-4ae2-4867-958a-2f27eb361cd9.png)

>took the getMd5 function outside as it was causing errors.
>tried to fix the indentation on idle but it isnt working here

@DinakaranP

**Comment by DinakaranP** [comment]
Can you try with four spaces or one tab 
@aarthiprashanth13
